### ISSUE TITLE
allow user config to use own random generator

### ISSUE THREAD

**Issue by mybigman** [ed-henrique/suk#1]

**Comment by ed-henrique** [comment]
Sure thing, that's quick to do. But how would it figure out which characters to use for the keys? Should I give the user an option to change the possible key characters string?

Something like this:

```go
func WithCustomPossibleKeyCharacters(chars []string) {
  // ...
}

func WithCustomRandomKeyGenerator(func (int) (string, error)) {
  // ...
}
```

Also, I'm open to suggestions for the function names, since they seem pretty large.

**Comment by mybigman** [comment]
You would only the need the one `WithCustomRandomKeyGenerator` since user generator would handle it all.

Your suk package only expects the returned `id, err := randomID(s.keyLength)` data.

**Comment by ed-henrique** [comment]
It's done.
